source 'https://rubygems.org'

# RubyおよびRailsのバージョン固定（プロジェクトの先頭に明示）
ruby '3.2.6'
gem 'rails', '~> 7.1.5', '>= 7.1.5.1'

# データベース
gem 'sqlite3', '>= 1.4'

# Webサーバー
gem 'puma', '>= 5.0'

# JSONテンプレート
gem 'jbuilder'

# ページネーション
gem 'kaminari'

# 本番・開発用共通設定
gem 'bootsnap', require: false
gem 'tzinfo-data', platforms: %i[windows jruby]

# パスワード認証
# Userモデルで has_secure_password を使うにはbcryptが必要
gem 'bcrypt', '~> 3.1.7'

# テスト関連
group :development, :test do
  gem 'annotate'
  gem 'debug', platforms: %i[mri windows]
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'rspec-rails'
end

group :development do
  gem 'rubocop', require: false
end
